# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Terraform_Plan
    displayName: TfPlan
    jobs:
    - job: Tfplan
      steps:
        - task: TerraformInstaller@2
        displayName: Install teraaform
        inputs:
          terraformVersion: 'latest'